#!/bin/sh
# postinst script for audisp-tacplus
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

augenrules # generate a new /etc/audit/auditd.rules if needed

# and restart auditd, so new rules take effect
deb-systemd-invoke restart auditd >/dev/null || true


#DEBHELPER#

exit 0
